{% set version = "0.2.4" %}

package:
  name: polytope
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/polytope/polytope-{{ version }}.tar.gz
  sha256: bfc7467f61708849e54ee45199bcc2ece47fb4b45bcb34a0f231f0a51c8f982f

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install ."

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - networkx >=1.6
    - numpy >=1.10.0
    - python >=2.7
    - scipy >=0.18.0
    - cvxopt >=1.2.5
    - pytest
    - matplotlib

test:
  imports:
    - polytope
  requires:
    - nose
    - matplotlib-base >=2.0.0
  commands:
    - python -m nose tests/
  source_files:
    - tests/*_test.py

about:
  home: https://pypi.org/project/polytope/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: "a toolbox for geometric operations on polytopes in any dimension"
  doc_url: https://tulip-control.github.io/polytope/

extra:
  recipe-maintainers:
    - DecBayComp
